// Monthly database backup — runs automatically on Netlify's schedule (see
// `config` at the bottom), needs no button press, no manual step.
//
// What it does:
//   1. Pulls every row from every table that holds business data, using
//      the SERVICE ROLE key — a powerful key that must NEVER be put in the
//      app's client code (unlike the anon key, which is already public).
//      It only lives here, as a Netlify environment variable, so it never
//      reaches a browser and can't be stolen off the website.
//   2. Builds one Excel workbook: a "Backup summary" sheet (row count per
//      table, and anything that failed) followed by one sheet per table.
//   3. Emails that workbook as an attachment to whoever you configure.
//      If anything went wrong, the subject says so instead of looking
//      like a normal backup.
//
// ---- One-time setup (do this in the Netlify dashboard, Site settings ->
// Environment variables) ----
//   SUPABASE_URL              = https://naweqyzfrxhmpvnlznbs.supabase.co
//   SUPABASE_SERVICE_ROLE_KEY = (Supabase dashboard -> Project Settings ->
//                                API -> "service_role" key — NOT the anon
//                                key already in the app. Keep this secret.)
//   RESEND_API_KEY             = (free at resend.com — used only to send
//                                 the backup email, nothing else)
//   BACKUP_EMAIL_TO            = the email address that should receive it
//                                 (e.g. the owner's email — can be a
//                                 comma-separated list for more than one)
//   BACKUP_EMAIL_FROM          = a "from" address Resend lets you send as
//
// Nothing is sent anywhere except the one email address you configure.

import ExcelJS from "exceljs";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const RESEND_API_KEY = process.env.RESEND_API_KEY;
const BACKUP_EMAIL_TO = process.env.BACKUP_EMAIL_TO;
const BACKUP_EMAIL_FROM = process.env.BACKUP_EMAIL_FROM;

// Every table that holds data worth restoring. `order` gives paging a
// stable sort (a page boundary must never shuffle rows). If a new table is
// added to the app later, add it here too or it won't be backed up.
// device_push_tokens is deliberately left out: those are regenerated by each
// phone the next time it opens the app, and are device credentials.
const TABLES = [
  { name: "jobs", order: "created_at.asc,id.asc" },
  { name: "customers", order: "created_at.asc,id.asc" },
  { name: "vehicles", order: "created_at.asc,id.asc" },
  { name: "quotes", order: "created_at.asc,id.asc" },
  { name: "team_members", order: "created_at.asc,id.asc" },
  { name: "service_roles", order: "sort_order.asc,id.asc" },
  { name: "service_categories", order: "sort_order.asc,id.asc" },
  { name: "service_treatments", order: "sort_order.asc,id.asc" },
  { name: "module_workflow_steps", order: "sort_order.asc,id.asc" },
  { name: "locations", order: "sort_order.asc,id.asc" },
  { name: "invoice_counters", order: "entity.asc,year.asc" },
  { name: "app_settings", order: "key.asc" },
  { name: "announcements", order: "created_at.asc,id.asc" },
  { name: "issue_reports", order: "created_at.asc,id.asc" },
  { name: "deletion_log", order: "deleted_at.asc,id.asc" },
  { name: "activity_log", order: "created_at.asc,id.asc" },
];

// Columns that must never be written into an emailed file. PINs are login
// secrets; a backup email is far less protected than the database.
const REDACTED_COLUMNS = { team_members: ["pin"] };

// Supabase caps any single response at 1000 rows no matter what is asked
// for, and does it silently — a plain select=* would quietly return only the
// first 1000 rows of a bigger table (activity_log is already past that).
const PAGE_SIZE = 1000;

// Excel refuses to open a workbook containing a cell longer than 32,767
// characters (photos and signatures are stored as base64 text and blow far
// past it).
const MAX_CELL_CHARS = 32000;

async function fetchTable({ name, order }) {
  const rows = [];
  for (let offset = 0; ; offset += PAGE_SIZE) {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/${name}?select=*&order=${order}&limit=${PAGE_SIZE}&offset=${offset}`,
      { headers: { apikey: SUPABASE_SERVICE_ROLE_KEY, Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}` } },
    );
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    const page = await res.json();
    rows.push(...page);
    if (page.length < PAGE_SIZE) break;
  }
  return rows;
}

// Excel cells can't hold nested objects/arrays directly, so JSON columns
// (history, service_types, etc.) are written as their JSON text — still
// fully readable, just not "native" Excel columns.
function flattenValue(v) {
  if (v === null || v === undefined) return "";
  const text = typeof v === "object" ? JSON.stringify(v) : v;
  if (typeof text === "string" && text.length > MAX_CELL_CHARS) {
    return `[omitted: ${text.length.toLocaleString("en-US")} characters of image/large data — too big for a spreadsheet cell; the full record is in the database and in the app's "Export Full Backup"]`;
  }
  return text;
}

async function buildWorkbook() {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Mr.CAP Backup";
  workbook.created = new Date();

  const summary = workbook.addWorksheet("Backup summary");
  const summaryHeader = summary.addRow(["Table", "Rows", "Status"]);
  summaryHeader.font = { bold: true };
  const failures = [];

  for (const table of TABLES) {
    const sheet = workbook.addWorksheet(table.name.slice(0, 31)); // Excel sheet name limit
    let rows;
    try {
      rows = await fetchTable(table);
    } catch (err) {
      sheet.addRow([`Could not fetch this table: ${err.message}`]);
      summary.addRow([table.name, "", `FAILED — ${err.message}`]);
      failures.push(table.name);
      continue;
    }
    summary.addRow([table.name, rows.length, "ok"]);
    if (!rows.length) {
      sheet.addRow(["(no rows)"]);
      continue;
    }
    const hidden = new Set(REDACTED_COLUMNS[table.name] || []);
    const columns = Object.keys(rows[0]).filter((c) => !hidden.has(c));
    const headerRow = sheet.addRow(columns);
    headerRow.font = { bold: true };
    for (const row of rows) {
      sheet.addRow(columns.map((c) => flattenValue(row[c])));
    }
    sheet.columns.forEach((col) => { col.width = 24; });
  }
  summary.columns = [{ width: 26 }, { width: 10 }, { width: 70 }];

  return { workbook, failures };
}

async function sendEmail({ subject, text, attachments }) {
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      from: BACKUP_EMAIL_FROM,
      to: BACKUP_EMAIL_TO.split(",").map((s) => s.trim()),
      subject,
      text,
      ...(attachments ? { attachments } : {}),
    }),
  });
  if (!res.ok) throw new Error(`Resend API error ${res.status}: ${(await res.text()).slice(0, 200)}`);
}

export default async () => {
  const missing = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "RESEND_API_KEY", "BACKUP_EMAIL_TO", "BACKUP_EMAIL_FROM"]
    .filter((key) => !process.env[key]);
  if (missing.length) {
    console.error("Monthly backup skipped — missing environment variables:", missing.join(", "));
    return new Response(`Missing environment variables: ${missing.join(", ")}`, { status: 500 });
  }

  const monthLabel = new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" });
  const dateStamp = new Date().toISOString().slice(0, 10);

  try {
    const { workbook, failures } = await buildWorkbook();
    const buffer = await workbook.xlsx.writeBuffer();
    const partial = failures.length > 0;
    await sendEmail({
      subject: `${partial ? "[INCOMPLETE] " : ""}Mr.CAP Database Backup — ${monthLabel}`,
      text: partial
        ? `The Mr.CAP backup for ${monthLabel} is INCOMPLETE — these tables could not be read: ${failures.join(", ")}.\n\nThe attached workbook has everything else; its "Backup summary" sheet lists what failed and why. Check the Netlify function log for monthly-backup.`
        : `Attached is the full Mr.CAP database backup for ${monthLabel} (as of ${dateStamp}).\n\nIt contains job cards, customers, vehicles, quotations, team (without PINs), service pricing, invoice counters, settings, announcements, issue reports, and the deletion and activity logs. The "Backup summary" sheet lists the row count for each table. Photos and signatures are too large for a spreadsheet, so they are left out of this file — the app's "Export Full Backup" button includes everything. Keep this somewhere safe (e.g. a dated folder in Google Drive).`,
      attachments: [{ filename: `mrcap-backup-${dateStamp}.xlsx`, content: Buffer.from(buffer).toString("base64") }],
    });
    console.log(partial ? `Monthly backup sent INCOMPLETE — failed: ${failures.join(", ")}` : "Monthly backup sent successfully.");
    return new Response(partial ? `Backup sent, but incomplete: ${failures.join(", ")}` : "Backup sent successfully", { status: partial ? 500 : 200 });
  } catch (err) {
    console.error("Monthly backup failed:", err);
    // A silent failure is the worst outcome for a backup: nobody finds out
    // until the day it's needed. Try to say so by email (this can only work
    // if the failure wasn't the email service itself).
    try {
      await sendEmail({
        subject: `[FAILED] Mr.CAP Database Backup — ${monthLabel}`,
        text: `The automatic Mr.CAP backup for ${monthLabel} did not run.\n\nReason: ${err.message}\n\nNothing was lost — this only means this month's backup file was not produced. Check the Netlify function log for monthly-backup, or use "Export Full Backup" in the app's Admin Dashboard in the meantime.`,
      });
    } catch (alertErr) {
      console.error("Could not send the failure alert either:", alertErr);
    }
    return new Response(`Backup failed: ${err.message}`, { status: 500 });
  }
};

// Runs at 03:00 UTC (07:00 Dubai time) on the 1st of every month.
export const config = {
  schedule: "0 3 1 * *",
};
